import Head from 'next/head';
import Header from '../components/Header';
import HeroSection from '../components/HeroSection';
import Features from '../components/Features';
import Process from '../components/Process';
import Faq from '../components/Faq';
import Footer from '../components/Footer';
import '../styles/Home.module.css';
import Before from '../components/Before';
export default function Home() {
  return (
    <>
      <Head>
        <title>Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <Features />
      <Process />
      <Before />
      <Faq />
      <Footer />
    </>
  );
}
